# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Computational Linguistic 2 - Universal Dependencies
baseurl: "/annodoc"
homeurl: "https://github.com/Andreapdr/annodoc/"
editurl: "https://github.com/Andreapdr/annodoc/edit/gh-pages"
test: "https://github.com/Andreapdr/annodoc/sandbox"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  relation:
    output: true

theme: jekyll-theme-minimal
