# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Computational Linguistics 2 - Universal Dependencies
baseurl: "/lc2"
homeurl: "https://github.com/Andreapdr/lc2/"
editurl: "https://github.com/Andreapdr/lc2/edit/gh-pages"

##############################################################################

# Collection settings

collections:
  entity:
    output: true
  relation:
    output: true

theme: jekyll-theme-minimal
