# Build settings

source: .
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Annodoc
homeurl: ""
editurl: "https://github.com/spyysalo/annodoc/edit/master"
issueurl: "https://github.com/spyysalo/annodoc/issues"

##############################################################################

# Collection settings

collections:
  type:
    output: true
